version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_php
        volumes:
            - ./:/var/www
        working_dir: /var/www
        depends_on:
            - db

    db:
        image: postgres:15
        container_name: laravel_pgsql
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: AppRegione
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
